### PR TITLE
Cumulus NVUE: Fix BGP communities being advertised

### LINKED ISSUE #1606: [BUG] CL NVUE: BGP community propagation is not configured correctly
* Test topology: https://github.com/ipspace/netlab/blob/dev/tests/integration/bgp/05-community.yml
* Validation results: https://tests.netlab.tools/cumulus_nvue/libvirt/bgp/05-community.yml-validate.log

I don't think this ever worked, and I'm OK to declare this a caveat and move on. What do you think @jbemmel?

### PR DESCRIPTION
**Pull request by jbemmel**
* Explicitly set to 'on' or 'off'
* Add neighbor description
* Treat ibgp_localas as ibgp
* Check bgp.next_hop_self

Fixes #1606

### CODE REVIEW

**Review by ipspace — CHANGES_REQUESTED** [review]
While this would pass the integration tests, it's different from most other configuration templates that use something along these lines:

```
{% if n.type in bgp.community|default({}) %}
{%   for c_type in bgp.community[n.type] %}
  neighbor {{ ip }} send-community {{ c_type }}
{%   endfor %}
{% endif %}
```

Important differences:

* Missing bgp.community.x means "we don't care" not "no communities"
* ibgp_localas is different from ibgp, allowing finer granularity if needed

**Comment by jbemmel** [comment]
Updated PR 

Could consider to extend the integration test to include ```ibgp_localas``` with a different set of communities

**Review by ipspace — APPROVED** [review]
Thank you!

**Comment by ipspace** [comment]
> Could consider to extend the integration test to include `ibgp_localas` with a different set of communities

Not all devices support IBGP local-as, so we'd have to create a new test just for that, and the integration tests already take around 48 hours to run, so I tend to skip edge cases (I could create way more integration tests were it not for time constraints)

**Pull request merged**
