### PR TITLE
Support for unmanaged devices (aka "ghosts")

### PR DESCRIPTION
**Pull request by ssasso**
NOTE: I created the "input" test but not the "expected" one - not sure how to generate it in this very specific case.

Addresses #547

### CODE REVIEW

**Comment by jbemmel** [comment]
You can run ```tests/create-transformation-tests.sh```

**Comment by ssasso** [comment]
> You can run `tests/create-transformation-tests.sh`

I don't think this will create a valid test for that specific case where the expected result should not have the *ghost* nodes in it.

**Review by jbemmel — CHANGES_REQUESTED** [review]
This approach is not going to work - Netlab needs to be aware of these unmanaged devices, allocate IP addresses for them, etc. Adding them to the topology and then removing them as a first step makes no sense; it would break all configuration logic

As discussed, I think these 'unmanaged' devices should be modeled as a new type of device ('unmanaged'). This device type would support all modules and features, but configuration would be a no-op ( i.e. empty script that does nothing, or skip condition in Ansible )

**Comment by ipspace** [comment]
Please note that the unmanaged devices are removed from the data model after the transformation has been complete -- in provider module(s) before generating configuration files (because they're "outside") and from Ansible inventory (because they are unmanaged).

**Comment by jbemmel** [comment]
> Please note that the unmanaged devices are removed from the data model after the transformation has been complete -- in provider module(s) before generating configuration files (because they're "outside") and from Ansible inventory (because they are unmanaged).

I apologize, I mis-glanced - the diff shows "def transform()" and then right below it the 'ghost_buster' routine - but it gets called after transformation, so that's ok

**Comment by ipspace** [comment]
Modified the test routines to support configurable "we don't want to see this" parameter, amended the commit and force-pushed it to dev-1.4 Thank you!

**Pull request merged**
