### PR TITLE
Replace gNMI plugin with srlinux ansible collection

### PR DESCRIPTION
**Pull request by jbemmel**
Due to lack of maintenance and support for the gnmi plugin, the Ansible galaxy collection is a better way forward

Obviously needs some further testing - will do that as I go forward

Could consider adding the installation of the collection to the 'Ansible' install script

### CODE REVIEW

**Comment by ipspace** [comment]
Based on "Obviously needs some further testing" I converted this PR to draft. When you're ready to merge it (= when the further testing proved it's safe to merge) please let me know and I'll merge it.

**Comment by ipspace** [comment]
According to @sdktr it looks like new versions of Ansible no longer work with the software installed with `netlab install grpc` (could be related to https://github.com/ansible/ansible/pull/79372). If that's the case, then it might be worthwhile getting this PR tested and merged.

**Comment by ipspace** [comment]
@jbemmel: Any progress on this or should we forget this whole idea?

**Comment by hellt** [comment]
I can help with the switch. I don't know the netlab parts, but know srlinux and its collection parts.
If there is a certain target state for each of the tasks I can assist in transition

**Comment by ipspace** [comment]
OK, I'm biting ;) As we have integration tests that should check most of the device configuration features, here's the plan:

* I managed to turn this PR into a local branch in this repository https://github.com/ipspace/netlab/tree/srlinux-json (@jbemmel's work is safe) 
* I did a rebase onto the current dev branch, added the device dependency on Ansible collection (a functionality we didn't have when this PR was created) and fixed a few YAML issues.
* I'll run the integration tests to see what breaks, and then we can start fixing stuff.

I can fix the obvious staff (looks like 'path' needs to start with a / and 'val' should become 'value'), but there are numerous other things that have to be fixed from the config correctness perspective, and I won't be able to fix those. FWIW, SR Linux is the most broken platform we're testing at the moment (see https://release.netlab.tools/ for details), so there will be a lot of things to fix.

Finally, what about SR OS?

**Comment by hellt** [comment]
> I can fix the obvious staff (looks like 'path' needs to start with a / and 'val' should become 'value'), but there are numerous other things that have to be fixed from the config correctness perspective, and I won't be able to fix those.

great plan, feel free to ping me when I can have a look at the test harness and the tests that require more involved attention.



> FWIW, SR Linux is the most broken platform we're testing at the moment

_SR Linux implementation within netlab_ might be the most broken, not SR Linux itself. fwiw it is the best NOS out there, objectively 😋

**Comment by ipspace** [comment]
> _SR Linux integration with netlab_ might be the most broken

Correct. Stupid me, didn't want to imply anything else 😎

> not SR Linux itself. fwiw it is the best NOS out there, objectively 😋

If you say so yourself 😜 But yeah, I have no problem with that claim ;)

**Comment by ipspace** [comment]
Replaced by #1291

**Pull request closed without merging**
