### PR TITLE
Add containerlab example to nodes docs

### PR DESCRIPTION
**Pull request by sdktr**
Document a working containerlab + sros example. Adds defaults and node specific overrides.

### CODE REVIEW

**Comment by ipspace** [comment]
Glad to see you joined netlab contributors. Welcome!

**Comment by jbemmel** [comment]
While I appreciate the contribution intent, I'm afraid this may confuse users - the way to select SR OS support, is to use a node of kind 'sros' - ~not~ clab.type: vr-sros

**Comment by ipspace** [comment]
@jbemmel Agreed, thanks for the feedback. I planned to rewrite the commit anyway and move the text to clab.md. Will use some strong language to point out one should NOT change clab.kind.

**Comment by ipspace** [comment]
@jbemmel Hope you're OK with changes in eff1e39

**Comment by jbemmel** [comment]
Yes, much better thanks

**Pull request merged**
