### PR TITLE
vJunos-switch baseline

### PR DESCRIPTION
**Pull request by ssasso**
vJunos-switch baseline - See #1253

### CODE REVIEW

**Comment by ipspace** [comment]
Where did you get the 'et-0/0' interfaces? This is what I see on the container:

```
admin@vswitch> show interfaces routing
Interface        State Addresses
ge-0/0/9.16386   Down
ge-0/0/8.16386   Down
ge-0/0/7.16386   Down
ge-0/0/6.16386   Down
ge-0/0/5.16386   Down
ge-0/0/4.16386   Down
ge-0/0/3.16386   Down
ge-0/0/2.16386   Up
ge-0/0/1.16386   Up
ge-0/0/0.16386   Up
pfe-0/0/0.16383  Up
pfh-0/0/0.16384  Up
pfh-0/0/0.16383  Up
lc-0/0/0.32769   Up    VPLS  enabled
lo0.16385        Up
lo0.16384        Up    INET  127.0.0.1
fxp0.0           Up    INET  10.0.0.15
em1.0            Up    INET  10.0.0.4
                       INET  128.0.0.1
                       INET  128.0.0.4
                       INET6 fe80::5254:ff:fe12:bdfe
                       INET6 fec0::a:0:0:4
```

**Comment by ssasso** [comment]
device readiness not working as expected :(

**Comment by ssasso** [comment]
> Where did you get the 'et-0/0' interfaces

from the containerlab documentation ... :(

**Comment by ipspace** [comment]
> > Where did you get the 'et-0/0' interfaces
> 
> from the containerlab documentation ... :(

There's a difference between theory and reality 🤦‍♂️

I'll merge the PR, change the settings if needed, and amend/force-push the commit.

**Comment by ipspace** [comment]
> device readiness not working as expected :(

I knew that dash would haunt us. Will figure out what's going on (don't want you to despair over my Ansible code).

**Comment by ipspace** [comment]
It wasn't the dash, but incorrect file extension (.yaml instead of .yml). I also modified the interface names and the readiness script to check the data-plane interfaces (similar to vPTX).

The initial documentation is done, now running integration tests.

**Pull request merged**
