### PR TITLE
AOS-CX: fixes for EVPN

### PR DESCRIPTION
**Pull request by ssasso**
AOS-CX: Fixes for EVPN broken integration testing:

* 05-vxlan-l3only
* 11-vxlan-ebgp
* 13-vxlan-ebgp-allowas
* 14-vxlan-ebgp-ebgp
* 22-ospf-ce-router

(ref: https://tests.netlab.tools/_html/arubacx-libvirt-evpn)

### CODE REVIEW

**Comment by ipspace** [comment]
Yeah, I thought it might have been the next hop problem. Please let me know when it's ready to be merged.

**Comment by ssasso** [comment]
Also the `allowas-in` must be forced for address family, and I'm looking also at the other failed tests.

I will let you know when everything is in place. :)

**Comment by ssasso** [comment]
* 04-vxlan-central-routing
* 20-vxlan-irb-ospf

still under investigation - but seems to have encountered some virtual device limitation...
(spine device is sending malformed packets)

(especially for 04 - for which I have a similar setup working, with physical devices)

**Comment by ssasso** [comment]
## 04-vxlan-central-routing

It seems there are some interop issues on Centralized IRB topologies:

* Leaf 1 Aruba CX, Leaf 2 FRR, Spine (Central IRB) Aruba CX (topology of the test) --> **broken** (*spine sends packets with wrong length field value in headers, linux is discarding it*)
*  Leaf 1 Aruba CX, Leaf 2 Aruba CX, Spine (Central IRB) Aruba CX (all devices same vendor) --> **working**
* Leaf 1 Aruba CX, Leaf 2 FRR, Spine (Central IRB) FRR --> **working**
* Leaf 1 FRR, Leaf 2 FRR, Spine (Central IRB) Aruba CX --> **broken**
* Leaf 1 Aruba CX, **Leaf 2 cEOS**, Spine (Central IRB) Aruba CX --> **checking**

---> documenting the device caveat for now.

**Comment by ipspace** [comment]
Looks like there's a bug in the software implementation of VXLAN-to-VXLAN routing on Aruba CX. Will add the caveat to the integration tests (so it shows as caveat not broken) when you're ready to merge this.

**Comment by ssasso** [comment]
A similar problem also applies to *20-vxlan-irb-ospf* :-(

Will rebase and force-push, then you can merge and add the caveats for the two integration tests.

thanks!

**Comment by ssasso** [comment]
Any 10.13 version will work

**Comment by ssasso** [comment]
@ipspace I just verified that **04-vxlan-central-routing** works fine if the other Leaf (`l2`) is Arista cEOS.

Can you try the same test with IOS-XE instead of FRR for `l2`?

```
root@hippo:~/GIT_H/netlab/tests/integration/evpn# netlab status
Lab default in /root/GIT_H/netlab/tests/integration/evpn
  status: started
  provider(s): clab

┏━━━━━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ node  ┃ device  ┃ image                            ┃ mgmt IPv4       ┃ connection  ┃ provider ┃ VM/container    ┃ status                 ┃
┡━━━━━━━╇━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━┩
│ h1    │ linux   │ python:3.9-alpine                │ 192.168.121.101 │ docker      │ clab     │ clab-evpn-h1    │ Up 9 minutes           │
├───────┼─────────┼──────────────────────────────────┼─────────────────┼─────────────┼──────────┼─────────────────┼────────────────────────┤
│ h2    │ linux   │ python:3.9-alpine                │ 192.168.121.102 │ docker      │ clab     │ clab-evpn-h2    │ Up 9 minutes           │
├───────┼─────────┼──────────────────────────────────┼─────────────────┼─────────────┼──────────┼─────────────────┼────────────────────────┤
│ h3    │ linux   │ python:3.9-alpine                │ 192.168.121.103 │ docker      │ clab     │ clab-evpn-h3    │ Up 9 minutes           │
├───────┼─────────┼──────────────────────────────────┼─────────────────┼─────────────┼──────────┼─────────────────┼────────────────────────┤
│ h4    │ linux   │ python:3.9-alpine                │ 192.168.121.104 │ docker      │ clab     │ clab-evpn-h4    │ Up 9 minutes           │
├───────┼─────────┼──────────────────────────────────┼─────────────────┼─────────────┼──────────┼─────────────────┼────────────────────────┤
│ l1    │ arubacx │ vrnetlab/vr-aoscx:20240129204649 │ 192.168.121.105 │ network_cli │ clab     │ clab-evpn-l1    │ Up 9 minutes (healthy) │
├───────┼─────────┼──────────────────────────────────┼─────────────────┼─────────────┼──────────┼─────────────────┼────────────────────────┤
│ l2    │ eos     │ ceos:4.32.1F                     │ 192.168.121.106 │ network_cli │ clab     │ clab-evpn-l2    │ Up 9 minutes           │
├───────┼─────────┼──────────────────────────────────┼─────────────────┼─────────────┼──────────┼─────────────────┼────────────────────────┤
│ spine │ arubacx │ vrnetlab/vr-aoscx:20240129204649 │ 192.168.121.107 │ network_cli │ clab     │ clab-evpn-spine │ Up 9 minutes (healthy) │
└───────┴─────────┴──────────────────────────────────┴─────────────────┴─────────────┴──────────┴─────────────────┴────────────────────────┘
root@hippo:~/GIT_H/netlab/tests/integration/evpn# netlab validate
[ping_red]  Intra-VLAN ping-based reachability test (red) [ node(s): h1 ]
[PASS]      h1: Ping to h2 succeeded
[PASS]      Test succeeded

[ping_blue] Intra-VLAN ping-based reachability test (blue) [ node(s): h3 ]
[PASS]      h3: Ping to h4 succeeded
[PASS]      Test succeeded

[ping_h3]   Inter-VLAN ping-based reachability test (red-to-blue) [ node(s): h1,h2 ]
[PASS]      h1: Ping to h3 succeeded
[PASS]      h2: Ping to h3 succeeded
[PASS]      Test succeeded

[ping_h1]   Inter-VLAN ping-based reachability test (blue-to-red) [ node(s): h3,h4 ]
[PASS]      h3: Ping to h1 succeeded
[PASS]      h4: Ping to h1 succeeded
[PASS]      Test succeeded

[SUCCESS]   Tests passed: 6
```

**Comment by ipspace** [comment]
It works with NX-OS. Will add that to the caveats.

**Pull request merged**
