### PR TITLE
MLAG support feature, initially for OS10 and EOS

### PR DESCRIPTION
**Pull request by jbemmel**
Depends on https://github.com/ipspace/netlab/pull/1541 (rebased)

* Add ```lag.mlag.peergroup``` on LAG links to model peerlinks
* Showcases 2 platforms with different approaches to peerlinks, modeling each case (fully configurable)
* Checks that the 'M' side of MLAG supports mlag and is the same device type
* Numbers lag interfaces consistently (same ifindex on all M-sides, starting from 1 on all 1-sides)
* Validated anycast gateway support

This works, on both OS10 and EOS:
```
vlans:
 red:
  gateway.protocol: anycast
links:
- lag: # MLAG peer links between S1 and S2
   members: [s1-s2,s1-s2]
   mlag.peergroup: 1
- lag:
   members: [ h1-s1,h1-s1,h1-s2,h1-s2 ]
   mlag: True
  vlan.access: red
- lag:
   members: [ h2-s1,h2-s1,h2-s2,h2-s2 ]
   mlag: True
  vlan.access: red
```

### CODE REVIEW

**Comment by jbemmel** [comment]
Note: Does not check or warn the user about missing mlag_peer link when mlag is being used; could be added

**Comment by jbemmel** [comment]
Debugging an issue with the VLAN module creating duplicate interfaces in an mlag case - put back to draft

**Comment by ipspace** [comment]
As you probably discovered by now, some of these ideas were not optimal.

> Adds a new link type `mlag_peer` to model peerlinks

Wrong. The MLAG peer link is just a point-to-point link like any other P2P link. Allowing the 'lag' link type was an error (in retrospect) and we'll not continue that bad practice.

Feel free to use **lag.something** (or **lag._something** if you don't want to define an attribute) to indicate a link is a peer link.

> Refactors the setting of `netlab_interfaces` to exclude links of type `mlag_peer` once (fixing some consistency issues with 'always' tag missing) -- could split this into a separate PR if you prefer

And yet again, you change a ton of unrelated things when your data model hits a wall. **netlab_interfaces** is a list of all interfaces in the box, and if you think some interfaces should be handled in a different way, then you should implement that in the initial configuration template.

I will review the rest of the code once you make/undo these changes.

**Comment by jbemmel** [comment]
Refactored to remove ```mlag_peer``` link type

High number of changed files is mainly due to ```virtual_interface``` being removed from vlan_members, same as PR #1541

**Comment by jbemmel** [comment]
Draft: Needs more work on the peer links (lag is implicit on some platforms)

**Comment by ipspace** [comment]
How about you mark a PR ready for review _after_ you push the last commit? Will start looking at it when you confirm it's ready for review.

**Comment by ipspace** [comment]
> this PR depends on #1541 which you finally merged yesterday.

I sincerely apologize for having a different set of priorities the last week. I did not understand it was THAT urgent.

**Review by ipspace — APPROVED** [review]
I did not look at the details. This will get merged, and then (if needed) we can streamline the integration tests and run them.

**Comment by jbemmel** [comment]
> > this PR depends on #1541 which you finally merged yesterday.
> 
> I sincerely apologize for having a different set of priorities the last week. I did not understand it was THAT urgent.

"finally" was not meant to criticize nor imply a notion of urgency - it simply took some back-and-forth discussion and then it was "finally" merged, which triggered me to update this pending PR (trying to save you some time and effort in the process)

Thank you for merging

**Pull request merged**
