### PR TITLE
Issue error when user tries to set access vlan attributes via an interface

### PR DESCRIPTION
**Pull request by jbemmel**
Suggestion for https://github.com/ipspace/netlab/discussions/1440

### CODE REVIEW

**Comment by ipspace** [comment]
Thanks for the suggestion. I think we need to be stricter than that -- everything that is not whitelisted should be banned. Is there anything (apart from the **vlan** attribute itself) that should be whitelisted?

**Comment by ipspace** [comment]
Replaced by #1445 (and thanks a million for finding the root cause of #1436)

**Comment by jbemmel** [comment]
> Thanks for the suggestion. I think we need to be stricter than that -- everything that is not whitelisted should be banned. Is there anything (apart from the **vlan** attribute itself) that should be whitelisted?

The code itself puts ‘’’ipv4: False’’’ on access vlan interfaces at times (and then removes it before producing the topology files)

**Comment by ipspace** [comment]
> The code itself puts ‘’’ipv4: False’’’ on access vlan interfaces at times (and then removes it before producing the topology files)

Thank you. Yeah, I found that out the hard way ;) It's included in #1445

**Pull request closed without merging**
