### PR TITLE
Fix routed trunk vlan mode

### PR DESCRIPTION
**Pull request by jbemmel**
* Not too early, when traversing global topology
* Fill it in when creating per-node vlan dict (if not set)

Fixes https://github.com/ipspace/netlab/issues/418

Note that the pattern of getting a parameter from node / if not from topology / if not default value seems generic, could add a helper method in data

### CODE REVIEW

**Review by ipspace — APPROVED** [review]
This looks almost exactly what's needed. The test cases are failing (no surprise there), so I'll merge this, then figure out why the test cases are failing, and add router-on-a-stick test case (because obviously we need it ;)

**Comment by jbemmel** [comment]
Actually, I think the test cases are failing because the fix is incomplete - there are some corner cases not covered. I'll try to isolate and create a smaller regression test case

**Comment by ipspace** [comment]
> Note that the pattern of getting a parameter from node / if not from topology / if not default value seems generic, could add a helper method in data

That's why I already added get_global_parameter, if we stumble upon a use case where we need the full three-level inheritance, we'll add another helper method.

BTW, this is not that use case, because we have to treat global VLANs differently from node VLANs.

Also, we need the "manual" inheritance only very early on the the life of a module, after the early hooks the core transformation routine takes care of proper inheritance. We do have to run the early hooks first otherwise modules can't influence each other (example: EVPN setting VXLAN flooding mode).

**Comment by ipspace** [comment]
> Actually, I think the test cases are failing because the fix is incomplete - there are some corner cases not covered. I'll try to isolate and create a smaller regression test case

Nope, it's just that **mode: irb** is missing in a number of places. I have to check whether that's only in global VLANs -- in that case we really don't care because they never get propagated to Ansible inventory.

**Comment by ipspace** [comment]
Done. Force-pushed the amended commit.

Thanks a million for fixing this!!!

**Comment by ipspace** [comment]
> > Note that the pattern of getting a parameter from node / if not from topology / if not default value seems generic, could add a helper method in data
> 
> That's why I already added get_global_parameter, if we stumble upon a use case where we need the full three-level inheritance, we'll add another helper method.

Just realized we also have `get_effective_module_attribute`. This thing is getting too big to handle mentally :(

**Pull request merged**
