### PR TITLE
Fix links to .md files with anchor

### PR DESCRIPTION
**Pull request by steffann**

### CODE REVIEW

**Comment by jbemmel** [comment]
Should this be applied to dev instead?

**Comment by ipspace** [comment]
That would have been better, but I do a rebase before merging anyway, so it doesn't hurt. I do wonder how @steffann managed to submit a PR against master branch though ;)

**Comment by steffann** [comment]
Good to know, thanks!

**Comment by ipspace** [comment]
> Good to know, thanks!

Thanks for becoming a contributor... and no worries, that thing would be impossible to know.

**Pull request merged**
