### PR TITLE
add eos-downloader info to docs

### PR DESCRIPTION
**Pull request by ryanmerolle**
Closes issue #580

Adds eos-downloaded to vEOS and cEOS documentation.

Thanks to @titom73 for making the package!

### CODE REVIEW

**Comment by ipspace** [comment]
Thank you. Will do a slight rewording after the merge, amend the commit and force-pushed it back (yeah, I prefer a cleaner commit history over the ability to blame missing dots to individual contributors ;)

**Comment by ipspace** [comment]
BTW, I removed

> The image is a tar archive that contains the EOS image and a license file. You will need to extract the EOS image from the archive and place it in the `images` directory of containerlab.

I always just downloaded the container, renamed the file, and imported the image. Am I missing something? What is the containerlab `images` directory?

**Comment by ryanmerolle** [comment]
I am playing with the GitHub copilot.  It auto suggests wording.  The wording adjustment you suggest make sense.

**Comment by ipspace** [comment]
> I am playing with the GitHub copilot. It auto suggests wording. The wording adjustment you suggest make sense.

Glad to hear I'm still marginally better than AI 🤣

**Pull request merged**
