### PR TITLE
Trim svi neighbor list to include only direct neighbors

### PR DESCRIPTION
**Pull request by jbemmel**
Fixes https://github.com/ipspace/netsim-tools/issues/325

### CODE REVIEW

**Comment by jbemmel** [comment]
This may be trimming too much, reading back the issue it is more about interfaces being part of different VRFs?

**Comment by ipspace** [comment]
Thanks a million for trying to solve this one, but it's more complex. We need full list of neighbors on L2 VLANs and just the local neighbors if all attached VLAN interfaces are L3 interfaces (example: multi-hop VRF Lite).

Will try to solve it in the next days, but the answer will never be precise without reinventing SPF, so maybe I'll just give up and do that. It's not like we'd be dealing with huge data sets.

**Comment by jbemmel** [comment]
The patch does fix the multi-hop VRF lite case:
```
- bridge_group: 2
  ifindex: 4
  ifname: ethernet-1/1.1
  ipv4: 172.16.6.1/24
  name: r1 -> [r2]
  neighbors:
  - ifname: ethernet-1/2.1
    ipv4: 172.16.8.2/24
    node: r2
  parent_ifindex: 1
  parent_ifname: ethernet-1/1
  type: vlan_member
  virtual_interface: true
  vlan:
    access_id: 1001
    mode: route
  vrf: blue
```

Is it "all attached VLAN interfaces" or only if the direct peer is routed?

**Comment by ipspace** [comment]
> The patch does fix the multi-hop VRF lite case:

That is true, but it returns wrong results for the "routed VLAN interfaces attached to a bridged network" case like `[tests/topology/expected/vlan-routed-vrf.yml](https://github.com/ipspace/netsim-tools/pull/357/files#diff-e37f3b915b08d73533c79191066bdc7276a8a8bfa26c27764a1d787517f96496)`.

In that test case, S1 and S2 are bridges, so R1 and R2 are neighbors on the same VLAN -- imagine what would happen if you were running OSPF.

**Comment by jbemmel** [comment]
Actually, none of the templates currently rely on the neighbors per interface. I only found
```
mpls/eos.6pe.j2: {% for l in interfaces|default([]) if l.type != 'stub' and l.neighbors is defined and not (l.ipv6|default(False)) %}
```

Perhaps an easier fix would be to remove the attribute altogether?

**Comment by ipspace** [comment]
We need link neighbors to set up EBGP sessions and to find a viable next hop for static routes on Linux hosts

**Comment by ipspace** [comment]
This has been fixed by [91047b6](https://github.com/ipspace/netlab/commit/91047b6eb24bad45a24aa5f32e38cc4c8bb50601)

**Pull request closed without merging**
