### PR TITLE
Changes to support ipv6 ebgp unnumbered with rfc8950 ipv4 forwarding

### PR DESCRIPTION
**Pull request by jbemmel**
In support of https://github.com/ipspace/netlab/issues/381

My topology:
```
addressing:
  fabric:
    # unnumbered: true # old style
    ipv4: true
    ipv6: true

bgp:
  as: 64999
  # sessions: # Transport sessions to use - leave at default
  #  ipv4: [ ibgp ] # IBGP-v4 over EBGP-v6
  #  ipv6: [ ebgp ]
  activate: # Address families to activate
    ipv4: [ ebgp ] # Only activate ipv4 over eBGP, use iBGP for EVPN only
```

### CODE REVIEW

**Review by ipspace — COMMENTED** [review]
I don't understand the need for changes to bgp.py. The current code is very careful to check that the enabled address families match on both ends.

What exactly are you trying to solve?

**Comment by jbemmel** [comment]
Those changes are needed to achieve the following:
```
neighbors:
  - activate:
      ipv4: false
    as: 64999
    evpn: true
    ipv4: 10.0.0.1
    name: spine
    rr: true
    type: ibgp
  - activate:
      ipv4: true    <-- added
      ipv6: false
    as: 65000
    ifindex: 49
    ipv4: true  <-- added
    ipv6: true
    local_as: 65001
    name: spine
    type: ebgp
```

Without the patch, there is nothing in the data model that says we want to enable ipv4 forwarding towards this neighbor, and activate the ipv4 address family in bgp

**Comment by jbemmel** [comment]
Alternatively we could update the logic in the bgp module based on the ipv4_rfc8950 feature - but currently the code assumes an ipv4 data path implies an ipv4 bgp session

**Comment by ipspace** [comment]
> Alternatively we could update the logic in the bgp module based on the ipv4_rfc8950 feature - but currently the code assumes an ipv4 data path implies an ipv4 bgp session

Got this as I was writing a reply to the previous comment. Yeah, I will check how ipv4_rfc8950 interacts with **bgp.sessions** attribute and document whatever turns out to be the "expected" ;) behavior. Blindly setting an address family for a neighbor is (IMO) too big a hammer in this particular case.

In any case, the code really assumes IPv4 data path implies IPv4 AF, but it could be on IPv4 transport session (if **ipv4** != True) and on IPv6 LLA transport session otherwise.

For the moment, try removing **bgp.sessions** attribute.

**Comment by jbemmel** [comment]
I did try that, that results in:
```
neighbors:
  - activate:
      ipv4: false
    as: 64999
    evpn: true
    ipv4: 10.0.0.1
    name: spine
    rr: true
    type: ibgp
  - activate:
      ipv4: true
    as: 64999
    ifindex: 1
    ipv4: 10.1.0.1  <-- not sure where this ip comes from, unwanted
    local_as: 65001
    name: h1
    type: ebgp <-- ipv4-only ebgp session, unwanted
  - activate:
      ipv4: true
      ipv6: false
    as: 65000
    ifindex: 49
    ipv4: true
    ipv6: true
    local_as: 65001
    name: spine
    type: ebgp
```

**Comment by ipspace** [comment]
No idea what’s going on, I would have to see the whole topology file…

**Comment by jbemmel** [comment]
## Testing topology for iBGP over eBGP with SR Linux

addressing:
  fabric:
    # unnumbered: true # old style
    ipv4: true
    ipv6: true

bgp:
  as: 64999
  # sessions: # Transport sessions to use
  #  ipv4: [ ibgp ] # IBGP-v4 over EBGP-v6
  #  ipv6: [ ebgp ]
  activate: # Address families to activate
    ipv4: [ ebgp ] # Only activate ipv4 over eBGP, use iBGP for EVPN only

provider: clab

groups:
  hosts:
    members: [ h1, h2, h3, h4 ]
    device: frr
    # module: [ bgp, evpn, vxlan, vlan, vrf ]
    module: [ bgp,evpn ]
  switches:
    members: [ spine, leaf1, leaf2 ]
    device: srlinux
    module: [ vlan,vxlan,bgp,evpn,vrf ]

vrfs:
  red:
  blue:

vlans:
  red:
    mode: route # To get an IP address for testing
    vrf: red
  blue:
    mode: bridge
    vrf: blue

vxlan.vlans: [ red, blue ]

# plugin: [ ebgp.ipv4-over-ipv6-lla ] # Enables ipv4 over ipv6 lla for ebgp sessions

nodes:
  spine:
    module: [ bgp,evpn ]
    bgp:
      local_as: 65000
      rr: True
      next_hop_self: False
  leaf1:
    bgp.local_as: 65001
    clab.startup-config: leaf1.cmd
  leaf2:
    bgp.local_as: 65002
  h1:
    # bgp.local_as: 65003 # Cannot be same as overlay, else AS loop
    vlans:
      red:
      blue:
  h2:
    # bgp.local_as: 65003 # Same for all hosts -> hosts do not accept specific routes to other hosts, only default
    vlans:
      red:
      blue:    
  h3:
  h4:

links:
- h1:
  leaf1:
    # vlan.access: red
    # bgp.originate:
    # - 0.0.0.0/1
    # - 128.0.0.0/1
  # role: fabric
- h2:
  leaf2:
    vlan.access: red
  # role: fabric
- h3:
  leaf1:
    vlan.access: blue
- h4:
  leaf2:
    vlan.access: blue

- spine:
   ifindex: 49
  leaf1:
   ifindex: 49
  role: fabric
- spine:
   ifindex: 50
  leaf2:
   ifindex: 49
  role: fabric

**Comment by jbemmel** [comment]
```
## Testing topology for iBGP over eBGP with SR Linux

addressing:
  fabric:
    # unnumbered: true # old style
    ipv4: true
    ipv6: true

bgp:
  as: 64999
  # sessions: # Transport sessions to use
  #  ipv4: [ ibgp ] # IBGP-v4 over EBGP-v6
  #  ipv6: [ ebgp ]
  activate: # Address families to activate
    ipv4: [ ebgp ] # Only activate ipv4 over eBGP, use iBGP for EVPN only

provider: clab

groups:
  hosts:
    members: [ h1, h2, h3, h4 ]
    device: frr
    # module: [ bgp, evpn, vxlan, vlan, vrf ]
    module: [ bgp,evpn ]
  switches:
    members: [ spine, leaf1, leaf2 ]
    device: srlinux
    module: [ vlan,vxlan,bgp,evpn,vrf ]

vrfs:
  red:
  blue:

vlans:
  red:
    mode: route # To get an IP address for testing
    vrf: red
  blue:
    mode: bridge
    vrf: blue

vxlan.vlans: [ red, blue ]

# plugin: [ ebgp.ipv4-over-ipv6-lla ] # Enables ipv4 over ipv6 lla for ebgp sessions

nodes:
  spine:
    module: [ bgp,evpn ]
    bgp:
      local_as: 65000
      rr: True
      next_hop_self: False
  leaf1:
    bgp.local_as: 65001
    clab.startup-config: leaf1.cmd
  leaf2:
    bgp.local_as: 65002
  h1:
    # bgp.local_as: 65003 # Cannot be same as overlay, else AS loop
    vlans:
      red:
      blue:
  h2:
    # bgp.local_as: 65003 # Same for all hosts -> hosts do not accept specific routes to other hosts, only default
    vlans:
      red:
      blue:    
  h3:
  h4:

links:
- h1:
  leaf1:
    # vlan.access: red
    # bgp.originate:
    # - 0.0.0.0/1
    # - 128.0.0.0/1
  # role: fabric
- h2:
  leaf2:
    vlan.access: red
  # role: fabric
- h3:
  leaf1:
    vlan.access: blue
- h4:
  leaf2:
    vlan.access: blue

- spine:
   ifindex: 49
  leaf1:
   ifindex: 49
  role: fabric
- spine:
   ifindex: 50
  leaf2:
   ifindex: 49
  role: fabric
```

**Comment by ipspace** [comment]
I would never try to figure out how to implement a new feature (or whether a change works) with a topology like that. It has way too many moving parts. I trimmed it down to the bare minimum to focus on the core topic (IPv4 AF over IPv6 LLA EBGP session):

```
addressing:
  fabric:
    ipv4: true
    ipv6: true

bgp:
  as: 64999
  activate:
    ipv4: [ ebgp ] # Only activate ipv4 over eBGP, use iBGP for EVPN only

provider: clab

groups:
  switches:
    members: [ spine, leaf1, leaf2 ]
    device: srlinux
    module: [ vlan,vxlan,bgp,evpn,vrf ]

nodes:
  spine:
    module: [ bgp,evpn ]
    bgp:
      local_as: 65000
      rr: True
      next_hop_self: False
  leaf1:
    bgp.local_as: 65001
  leaf2:
    bgp.local_as: 65002

links:
- spine:
   ifindex: 49
  leaf1:
   ifindex: 49
  role: fabric
- spine:
   ifindex: 50
  leaf2:
   ifindex: 49
  role: fabric
```

When using this topology with the latest code in the **dev** branch (which includes the changes to BGP neighbor flags we discussed yesterday), I get this results for the leaf node:

```
% ../netlab create -o yaml:nodes.leaf1.bgp
activate:
  ipv4:
  - ebgp
advertise_loopback: true
as: 64999
community:
  ebgp:
  - standard
  ibgp:
  - standard
  - extended
ipv4: true
ipv6: true
local_as: 65001
neighbors:
- activate:
    ipv4: false
  as: 64999
  evpn: true
  ipv4: 10.0.0.1
  name: spine
  rr: true
  type: ibgp
- activate:
    ipv4: true
    ipv6: false
  as: 65000
  ifindex: 49
  ipv4: true
  ipv4_rfc8950: true
  ipv6: true
  local_as: 65001
  local_if: ethernet-1/49
  name: spine
  type: ebgp
next_hop_self: true
router_id: 10.0.0.2
```

I would say that's exactly what's needed, if you feel something else needs to be fixed, please let me know.

I would also suggest we close this overcommented PR and start a fresh one with potential changes needed in the SR Linux configuration templates.

**Comment by jbemmel** [comment]
Closing to submit updated PR

**Pull request closed without merging**
