### PR TITLE
#1058 add type int for netlab status instance

### PR DESCRIPTION
**Pull request by sdargoeuves**
My first Pull Request via fork, it's not about the fix (it's the simplest fix I could think of!) it's about learning how to do more git things, for hopefully more things to come in the future!

### CODE REVIEW

**Comment by ipspace** [comment]
Welcome to the club ;) So nice to see another contributor. Unfortunately, the "instance ID" could be a string (example: "default") or an integer, the integer case arising only because of peculiarities of YAML- and `--set` option parsing.

To fix this one, we have to modify https://github.com/ipspace/netlab/blob/dev/netsim/cli/status.py#L53 to return str or int (`Union[str,int]`), and to try str and int value during the `lab_states` lookup process. Would you like to solve that or shall I implement the fix?

**Comment by sdargoeuves** [comment]
I knew that fix would be too simple! thanks for the comment and the help. I've added the suggested fix, where the instance_id can now be a `str` or a `int`

**Review by ipspace — COMMENTED** [review]
Reading the documentation for "isdigit()" I wonder whether everything that is recognized as having digits (ex: superscripts) would go work with int. Personally, I would go for something along the lines of "try: int(args.instance) except: args.instance"

Also, we're now expecting that a string parseable as integer will always appear as an integer key in lab_states. That is _probably_ true, but I can easily generate a counterexample (but then people shouldn't use too-smart tricks, right).

Anyway, let's go with this one until someone complains ;)

**Comment by ipspace** [comment]
Ouch, the changes made mypy decidedly grumpy. Never mind, I'll merge the PR, make the necessary adjustments, and amend the commit (yeah, I know I'm probably violating a half-dozen best practices).

**Comment by sdargoeuves** [comment]
That's a good point, I don't have any strong reason why I went with the `isdigit` rather than a `try... except...`, it seemed like a good enough way of doing that check, without thinking of the odd cases, like superscript.
If someone complains I'd be happy to change this to a try/except method.
Thank you for the updates and the merge!

**Pull request merged**
