### PR TITLE
Add support for containerized VyOS.

### PR DESCRIPTION
**Pull request by sysoleg**
We can't use the official 1.3-epa2 image from Docker Hub because it's outdated and doesn't work correctly with virtual network devices [1]. The thing is critical for the container environment with veth devices. Hence for now we can use the unofficial image [2] that is based on VyOS nightly ISO.

1. https://github.com/vyos/vyos-1x/commit/8cf5a4f023c5459cad4c84e93f73a9ddd69be81a
2. https://github.com/sysoleg/vyos-container

### CODE REVIEW

**Comment by ipspace** [comment]
@sysoleg Great job!
@ssasso Would you please review this one?

Thank you!

**Comment by ssasso** [comment]
> for i in shell:
>       args.append(i)

yes, I know, this can be better written as:

```
args = ['docker','exec','-it',host] + shell + ['-il']
```

**Comment by ipspace** [comment]
The change to `docker_shell` handling in **netlab connect** is in fc32654 (because it's the right thing to do). In any case, the discussion is moot as `docker exec` usually connects to the container as root (**cml** is a Cumulus VX node):

```
$ netlab connect -v cml
Connecting to container clab-X-cml, starting bash
Executing: ['docker', 'exec', '-it', 'clab-X-cml', 'bash', '-il']
Use vtysh to connect to FRR daemon

cml(bash)#whoami
root
```

@ssasso @sysoleg: Are we good to go?

**Comment by sysoleg** [comment]
@ipspace ``su - vyos`` will be enough. Check my latest commit.

**Comment by ssasso** [comment]
thanks a lot to both of you @ipspace and @sysoleg ! :-)

**Pull request merged**
