### PR TITLE
frr ipv6 disabled fixes

### PR DESCRIPTION
**Pull request by jbemmel**
* Disable ipv6 ND when ipv6 is not configured (frr bug prevents this from getting applied)
* Don't enable ipv6 forwarding when ipv6 is disabled
* Explicitly disable ipv6 on interfaces without ipv6 enabled, under Linux

### CODE REVIEW

**Review by ipspace — CHANGES_REQUESTED** [review]
Good catch on the BGP conditional logic. However...

* FRR IPv6 forwarding is (IIRC) enabled by default, so...
* Changing FRR IPv6 forwarding does nothing to the "disable IPv6" system flag
* Your implementation will disable unnumbered BGP sessions in IPv4-only lab unless we implement #460 by setting 'ipv6: True'
* You copied my incomplete implementation (yeah, I know). The same stuff has to be done on VLAN interfaces and subinterfaces (that's why I hate it so much).

**Comment by jbemmel** [comment]
I hit this during https://github.com/ipspace/netlab/pull/458, when I used ```unnumbered: True``` instead of ```ipv4/ipv6: True```
It was working with frr, but not with srlinux

For consistency, I figured it would be better to require the user to set ```ipv6: True``` for this use case, given that it requires ipv6 enabled on the link

**Comment by jbemmel** [comment]
I'm only trying to be explicit and technically accurate/intuitive. If you think that the audience prefers/expects ```ipv4: True``` (and by association ```unnumbered: True```) to enable ipv6 lla under the hood, then we can make it work like that too

**Comment by ipspace** [comment]
> I'm only trying to be explicit and technically accurate/intuitive. If you think that the audience prefers/expects `ipv4: True` (and by association `unnumbered: True`) to enable ipv6 lla under the hood, then we can make it work like that too

The audience expects 'ipv4: True' to work with unnumbered EBGP sessions just like the vendor promised ;) It turns out that the vendor promises depend on the unmentioned fact that their distro of Linux happens to have IPv6 enabled on all interfaces 🤷‍♂️

**Review by ipspace — CHANGES_REQUESTED** [review]
'ipv6: false' is removed from the interface somewhere in link transformation code, so there's no need to check for that. 'l.ipv6 is not defined' is good enough.

**Pull request merged**
