### PR TITLE
#1418 - vrrp no preempt needs to be explicit on cEOS

### PR DESCRIPTION
**Pull request by sdargoeuves**
#1418 - simple tweak to force the `no vrrp <group> preempt`

### CODE REVIEW

**Comment by sdargoeuves** [comment]
I've just been thinking about it, do you think we should change the default to be True, so if it's not specified, preemption will be enabled?

**Comment by ipspace** [comment]
There are two independent issues here:

* What is the default value of **gateway.vrrp.preempt** parameter
* How to configure that on Arista EOS

Will open another issue on the first one, once that's settled, you might have to change the `|default` bit. Other than that, the code looks good.

**Comment by ipspace** [comment]
> Edit: It seems to be how cEOS behaves, if you don't specify `no vrrp <group> preempt` the default behaviour is to enable preemption. So I feel like changing the default to True follows the same principle.

I don't want different devices to have different configuration template behavior or different default values. We have to agree on what the default is (please comment in #1420, "do nothing" is an option) and then ensure all configuration templates are consistent with that.

**Comment by sdargoeuves** [comment]
## Tests Results

| Platform | Preempt False | Preempt True | Preempt Default | Status |
|:---------|:--------------|:-------------|:----------------|:-------|
| ArubaCX | Disabled | Enabled | Enabled | ✅ |
| Cumulus | Disabled | Enabled | Enabled | ✅ |
| DellOS | not tested |-|-|❔|
| EOS | Disabled | Enabled | Enabled | ✅ |
| FRR | Disabled | Enabled | Enabled | ✅ |
| IOS | Disabled | Enabled | Enabled | ✅ |
| NXOS | not tested |-|-|❔|
| SRLinux | N/A | N/A |
| SROS | not tested |-|-|❔|
| VyOS | Disabled | Enabled | Enabled | ✅ |

I haven't got SROS not DellOS currently, but looking at the code, both should work as expected

**Comment by sdargoeuves** [comment]
@ipspace thank you for the doc update and the merge #1419 
I was wondering if you already have a (draft) page for the next release notes. We should mention the change of behaviour, as topology using the default, could result in a different state.
Maybe you already have some magic happening to capture all those changes, and update this part just before the new version is released.

**Comment by ipspace** [comment]
> I was wondering if you already have a (draft) page for the next release notes.

`docs/release/1.9.md`, but I haven't started the release 1.9.2 yet.

> Maybe you already have some magic happening to capture all those changes, and update this part just before the new version is released.

**git changelog** from https://github.com/tj/git-extras followed by some copy-paste-sorting. Don't worry about that (but thank you!), I do it before pushing out the release.

**Pull request merged**
