### PR TITLE
Change the FRR Vagrant box to Debian bookworm

### LINKED ISSUE #1595: Find a better VM to run FRRouting
FRRouting currently uses Ubuntu 20.04 as later versions of Ubuntu tend to be multi-interface-challenged. Ubuntu 20.04 comes with Python 3.8 which barely works with Ansible 11.0 (see #1590 for details).

We need to find a long-term solution for FRR virtual machines (Debian?)

### PR DESCRIPTION
**Pull request by ipspace**
Fixes #1595

Also: includes a YAML validation fix for an unrelated file

### CODE REVIEW

**Review by jbemmel — APPROVED** [review]
Should we change it for the generic Linux device as well?
```netsim/devices/linux.yml``` is the last one still using old Ubuntu

**Review by jbemmel — APPROVED** [review]
Should we also change the default Linux device?

**Comment by jbemmel** [comment]
> Should we also change the default Linux device?

See https://github.com/ipspace/netlab/pull/1622

**Comment by ipspace** [comment]
> Should we also change the default Linux device?

Absolutely. Same challenge.

**Comment by jbemmel** [comment]
In hindsight, this PR is missing some required changes to SSH private key handling - see https://github.com/ipspace/netlab/pull/1623

**Comment by ipspace** [comment]
> In hindsight, this PR is missing some required changes to SSH private key handling - see #1623

In hindsight, this PR works and does not break everything else as opposed to #1623.

**Pull request merged**
