### PR TITLE
Remove promise to forward LACP; it doesn't work

### PR DESCRIPTION
**Pull request by jbemmel**
For Netlab purposes, the main point is LLDP forwarding

### CODE REVIEW

**Review by ipspace — CHANGES_REQUESTED** [review]
If you want to be pedantic, get it right ;) netlab cares about LLDP and STP.

**Comment by jbemmel** [comment]
> If you want to be pedantic, get it right ;) netlab cares about LLDP and STP.

Yes, but the type of STP we care most about also isn't forwarded :(

```
MAC address	Protocol
*BLOCKED* 01-80-C2-00-00-00	Spanning Tree (STP/RSPT/MSTP)
*BLOCKED* 01-80-C2-00-00-01	Ethernet Flow Control (pause frames)
*BLOCKED* 01-80-C2-00-00-02	Link Aggregation Control Protocol (LACP)
01-80-C2-00-00-03	802.1X Port-Based Network Access Control
01-80-C2-00-00-08	Provider Bridge protocols (STP)[[2]](https://interestingtraffic.nl/2017/11/21/an-oddly-specific-post-about-group_fwd_mask/#fn2)
01-80-C2-00-00-0D	Provider Bridge protocols (MVRP)
01-80-C2-00-00-0E	802.1AB Link Layer Discovery Protocol (LLDP)[[3]](https://interestingtraffic.nl/2017/11/21/an-oddly-specific-post-about-group_fwd_mask/#fn3)
```

Netlab isn't doing anything yet with "Provider Bridge protocols", out of that list it's only LLDP

I'm happy to put any message you deem suitable, but "LACP" needs to be removed

**Comment by DanPartelly** [comment]
> > If you want to be pedantic, get it right ;) netlab cares about LLDP and STP.
> 
> Yes, but the type of STP we care most about also isn't forwarded :(
> 
> ```
> MAC address	Protocol
> *BLOCKED* 01-80-C2-00-00-00	Spanning Tree (STP/RSPT/MSTP)
> *BLOCKED* 01-80-C2-00-00-01	Ethernet Flow Control (pause frames)
> *BLOCKED* 01-80-C2-00-00-02	Link Aggregation Control Protocol (LACP)
> 01-80-C2-00-00-03	802.1X Port-Based Network Access Control
> 01-80-C2-00-00-08	Provider Bridge protocols (STP)[[2]](https://interestingtraffic.nl/2017/11/21/an-oddly-specific-post-about-group_fwd_mask/#fn2)
> 01-80-C2-00-00-0D	Provider Bridge protocols (MVRP)
> 01-80-C2-00-00-0E	802.1AB Link Layer Discovery Protocol (LLDP)[[3]](https://interestingtraffic.nl/2017/11/21/an-oddly-specific-post-about-group_fwd_mask/#fn3)
> ```
> 
> Netlab isn't doing anything yet with "Provider Bridge protocols", out of that list it's only LLDP
> 
> I'm happy to put any message you deem suitable, but "LACP" needs to be removed

Open vSwitch fabrics.

**Review by ipspace — APPROVED** [review]

**Comment by ipspace** [comment]
> Netlab isn't doing anything yet with "Provider Bridge protocols", out of that list it's only LLDP

Fair point. My kernel won't even allow me to change the low-order three bits.

> I'm happy to put any message you deem suitable, but "LACP" needs to be removed

Guess we're back to where we started ;))

**Comment by ipspace** [comment]
Also, would you use better commit messages than "Update linuxbridge.py" (because the commit message is used when merging a single-commit PR), or are we already at https://www.xkcd.com/1296/

**Pull request merged**
